/**
 * Single source of truth for all design tokens.
 * Swapping the entire visual identity = editing this file only.
 *
 * Rules:
 *   - No color hex, font name, or spacing value may appear outside this file.
 *   - Components reference CSS variables (e.g. var(--color-primary)).
 *   - CSS variables are generated by buildThemeCss() and injected in layout.tsx.
 *   - Font loading is done in layout.tsx via next/font/google, using the
 *     variable names and configuration exported from fontConfig below.
 */

// ─── PRIMITIVE COLORS ─────────────────────────────────────────────────────────

const navy = {
  900: '#0F2440',
  800: '#1B3A5C',
  700: '#224878',
} as const

const bronze = {
  600: '#B8862E',
  500: '#C9973A',
  100: '#F5ECD8',
} as const

const warm = {
  50:  '#F8F7F4',
  100: '#EDEAE4',
  200: '#D6D2C8',
} as const

const gray = {
  500: '#6B7280',
  900: '#141414',
} as const

const fixed = {
  white:         '#FFFFFF',
  forest700:     '#2D6A4F',
  red600:        '#DC2626',
  whatsapp:      '#25D366',
  whatsappHover: '#20B958',
} as const

// ─── SEMANTIC COLORS ──────────────────────────────────────────────────────────

export const colors = {
  // Surfaces
  bg:            warm[50],
  fg:            gray[900],

  // Brand — discipline & trust
  primary:       navy[800],
  primaryHover:  navy[900],
  primaryFg:     fixed.white,

  // Accent — achievement & measurement
  accent:        bronze[600],
  accentHover:   bronze[500],
  accentTint:    bronze[100],
  accentFg:      fixed.white,

  // Cards
  card:          fixed.white,
  cardFg:        gray[900],

  // Muted / secondary
  muted:         warm[100],
  mutedFg:       gray[500],

  // Structural
  border:        warm[200],
  ring:          navy[800],
  sectionAlt:    warm[100],

  // Status
  success:       fixed.forest700,
  error:         fixed.red600,
  errorFg:       fixed.white,

  // WhatsApp CTA — isolated, never used as a brand color
  whatsapp:      fixed.whatsapp,
  whatsappHover: fixed.whatsappHover,
} as const

// ─── FONT CONFIGURATION ───────────────────────────────────────────────────────
// layout.tsx imports these to configure next/font/google.
// Changing fontConfig changes what loads — no other file needs touching.

export const fontConfig = {
  display: {
    // H1, H2, H3, section labels, CTA text
    googleName:  'Cairo',
    variable:    '--font-display',
    subsets:     ['arabic'] as const,
    weights:     ['400', '500', '600', '700', '800'] as const,
    fallback:    "'Noto Sans Arabic', Arial, sans-serif",
  },
  body: {
    // Body copy, form labels, captions, FAQ answers
    googleName:  'IBM_Plex_Sans_Arabic',
    variable:    '--font-body',
    subsets:     ['arabic'] as const,
    weights:     ['300', '400', '500', '600'] as const,
    fallback:    "'Noto Sans Arabic', Tahoma, sans-serif",
  },
  mono: {
    // Numbers ONLY: kg, cm, prices, week numbers, phase numbers, stats
    googleName:  'IBM_Plex_Mono',
    variable:    '--font-mono',
    subsets:     ['latin'] as const,
    weights:     ['400', '500', '600', '700'] as const,
    fallback:    "'Courier New', monospace",
  },
} as const

// ─── SPACING ──────────────────────────────────────────────────────────────────

export const spacing = {
  1:  '0.25rem',   //  4px
  2:  '0.5rem',    //  8px
  3:  '0.75rem',   // 12px
  4:  '1rem',      // 16px
  5:  '1.25rem',   // 20px
  6:  '1.5rem',    // 24px
  8:  '2rem',      // 32px
  10: '2.5rem',    // 40px
  12: '3rem',      // 48px
  16: '4rem',      // 64px
  20: '5rem',      // 80px
  24: '6rem',      // 96px
} as const

// ─── RADIUS ───────────────────────────────────────────────────────────────────

export const radius = {
  sm:   '0.25rem',
  md:   '0.375rem',
  lg:   '0.5rem',
  xl:   '0.75rem',
  '2xl':'1rem',
  full: '9999px',
} as const

// ─── SHADOWS ──────────────────────────────────────────────────────────────────

export const shadows = {
  sm:  '0 1px 2px 0 rgb(0 0 0 / 0.05)',
  md:  '0 1px 3px 0 rgb(0 0 0 / 0.08), 0 1px 2px -1px rgb(0 0 0 / 0.08)',
  lg:  '0 4px 6px -1px rgb(0 0 0 / 0.08), 0 2px 4px -2px rgb(0 0 0 / 0.08)',
  xl:  '0 10px 15px -3px rgb(0 0 0 / 0.08), 0 4px 6px -4px rgb(0 0 0 / 0.08)',
} as const

// ─── MOTION ───────────────────────────────────────────────────────────────────

export const motion = {
  fast:   '150ms',
  normal: '200ms',
  slow:   '300ms',
  ease:   'cubic-bezier(0.4, 0, 0.2, 1)',
} as const

// ─── CSS VARIABLE GENERATOR ───────────────────────────────────────────────────
// Called in layout.tsx to inject :root { ... } at runtime.
// Font variables (--font-display etc.) are set by next/font, not here.

export function buildThemeCss(): string {
  return `
    /* Surfaces */
    --color-bg: ${colors.bg};
    --color-fg: ${colors.fg};

    /* Brand */
    --color-primary: ${colors.primary};
    --color-primary-hover: ${colors.primaryHover};
    --color-primary-fg: ${colors.primaryFg};

    /* Accent */
    --color-accent: ${colors.accent};
    --color-accent-hover: ${colors.accentHover};
    --color-accent-tint: ${colors.accentTint};
    --color-accent-fg: ${colors.accentFg};

    /* Cards */
    --color-card: ${colors.card};
    --color-card-fg: ${colors.cardFg};

    /* Muted */
    --color-muted: ${colors.muted};
    --color-muted-fg: ${colors.mutedFg};

    /* Structural */
    --color-border: ${colors.border};
    --color-ring: ${colors.ring};
    --color-section-alt: ${colors.sectionAlt};

    /* Status */
    --color-success: ${colors.success};
    --color-error: ${colors.error};
    --color-error-fg: ${colors.errorFg};

    /* WhatsApp */
    --color-whatsapp: ${colors.whatsapp};
    --color-whatsapp-hover: ${colors.whatsappHover};

    /* Spacing */
    --space-1:  ${spacing[1]};
    --space-2:  ${spacing[2]};
    --space-3:  ${spacing[3]};
    --space-4:  ${spacing[4]};
    --space-5:  ${spacing[5]};
    --space-6:  ${spacing[6]};
    --space-8:  ${spacing[8]};
    --space-10: ${spacing[10]};
    --space-12: ${spacing[12]};
    --space-16: ${spacing[16]};
    --space-20: ${spacing[20]};
    --space-24: ${spacing[24]};

    /* Radius */
    --radius-sm:   ${radius.sm};
    --radius-md:   ${radius.md};
    --radius-lg:   ${radius.lg};
    --radius-xl:   ${radius.xl};
    --radius-2xl:  ${radius['2xl']};
    --radius-full: ${radius.full};

    /* Shadows */
    --shadow-sm: ${shadows.sm};
    --shadow-md: ${shadows.md};
    --shadow-lg: ${shadows.lg};
    --shadow-xl: ${shadows.xl};

    /* Motion */
    --motion-fast:   ${motion.fast};
    --motion-normal: ${motion.normal};
    --motion-slow:   ${motion.slow};
    --motion-ease:   ${motion.ease};
  `
}
